#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/beckham

PRODUCT_COPY_FILES += \
    vendor/motorola/beckham/proprietary/system/etc/firmware/upd-00000126-00001001-fed70128-fffe0001-02.tftf:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/upd-00000126-00001001-fed70128-fffe0001-02.tftf \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.aov.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.aov.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.mod.protocols.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod.protocols.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.mod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.mod_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod_config.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.mod_v2.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod_v2.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/privapp-permissions-com.motorola.camera2.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.motorola.camera2.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/privapp-permissions-com.motorola.modservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.motorola.modservice.xml \
    vendor/motorola/beckham/proprietary/system/etc/permissions/privapp-permissions-com.motorola.projectormod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.motorola.projectormod.xml \
    vendor/motorola/beckham/proprietary/system/etc/sysconfig/hiddenapi-whitelist-com.motorola.modservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-com.motorola.modservice.xml \
    vendor/motorola/beckham/proprietary/system/etc/sysconfig/hiddenapi-whitelist-com.motorola.projectormod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-com.motorola.projectormod.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/beckham/proprietary/vendor/etc/ap_gain.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain.bin \
    vendor/motorola/beckham/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/beckham/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/camera/mot_ov5675_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_ov5675_chromatix.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/camera/mot_s5k4h7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_s5k4h7_chromatix.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/camera/s5k2l7sa_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7sa_chromatix.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-beckham.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-beckham.rc \
    vendor/motorola/beckham/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/motorola/beckham/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/motorola/beckham/proprietary/vendor/etc/init/motorola.hardware.health@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health@1.0-service.rc \
    vendor/motorola/beckham/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_cmd_smd_1080p_601.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_cmd_smd_1080p_601.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_cmd_tianma_1080p_601.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_cmd_tianma_1080p_601.xml \
    vendor/motorola/beckham/proprietary/vendor/etc/zaf/zaf_imx386.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_imx386.json \
    vendor/motorola/beckham/proprietary/vendor/etc/zaf/zaf_imx386_mono.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_imx386_mono.json \
    vendor/motorola/beckham/proprietary/vendor/etc/zaf/zaf_mot_s5k2l7sa.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_mot_s5k2l7sa.json \
    vendor/motorola/beckham/proprietary/vendor/firmware/MotorolaCapSense.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/MotorolaCapSense.hex \
    vendor/motorola/beckham/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/beckham/proprietary/vendor/firmware/moon-dsp1-ultrasound.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/moon-dsp1-ultrasound.bin \
    vendor/motorola/beckham/proprietary/vendor/firmware/moon-dsp1-ultrasound.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/moon-dsp1-ultrasound.wmfw \
    vendor/motorola/beckham/proprietary/vendor/firmware/moon-dsp2-aov-frontend.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/moon-dsp2-aov-frontend.wmfw \
    vendor/motorola/beckham/proprietary/vendor/firmware/moon-dsp2-aov-vrgain.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/moon-dsp2-aov-vrgain.bin \
    vendor/motorola/beckham/proprietary/vendor/firmware/moon-dsp3-aov-control.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/moon-dsp3-aov-control.wmfw \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.rx.ext.config.0:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.rx.ext.config.0 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.rx.ext.config.1:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.rx.ext.config.1 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.rx.ext.config.2:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.rx.ext.config.2 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.rx.ext.config.3:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.rx.ext.config.3 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.tx.ext.config.0:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.tx.ext.config.0 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.tx.ext.config.1:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.tx.ext.config.1 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.tx.ext.config.2:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.tx.ext.config.2 \
    vendor/motorola/beckham/proprietary/vendor/firmware/opalum.tx.ext.config.3:$(TARGET_COPY_OUT_VENDOR)/firmware/opalum.tx.ext.config.3 \
    vendor/motorola/beckham/proprietary/vendor/firmware/synaptics-smd-s3706b-18020101-298a66-beckham-dvt1a.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-smd-s3706b-18020101-298a66-beckham-dvt1a.tdat \
    vendor/motorola/beckham/proprietary/vendor/firmware/synaptics-smd-s3706b-18020101-298a66-beckham-evt.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-smd-s3706b-18020101-298a66-beckham-evt.tdat \
    vendor/motorola/beckham/proprietary/vendor/firmware/synaptics-smd-s3706b-18060602-29dc70-beckham.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-smd-s3706b-18060602-29dc70-beckham.tdat \
    vendor/motorola/beckham/proprietary/vendor/firmware/synaptics-tianma-s3706a-18060801-29dce7-beckham.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-tianma-s3706a-18060801-29dce7-beckham.tdat

PRODUCT_PACKAGES += \
    libmodmanager_system \
    libmodhw \
    libvibratorhw \
    motorola.hardware.vibrator@1.0 \
    com.motorola.mod@1.0_vendor \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    gatekeeper.sdm660 \
    libQSEEComAPI \
    libcdsprpc \
    libdualcameraddm \
    libiio \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libmcf-qc-fd-offline \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmodmanager \
    libsensor1 \
    libsensor_reg \
    libvideobokeh \
    sensor_calibrate \
    sensors.iio \
    sensors.rp \
    sensors.ssc \
    camera.sdm660 \
    libSonyDefocus \
    libS5k2l7Pdaf \
    libS5k2l7PdafCamif \
    lib_mot_app6_metadata \
    lib_mot_led_calibration \
    lib_motsensorlistener \
    libactuator_mot_ak7371 \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libchromatix_imx386_4k_video_3a \
    libchromatix_imx386_common \
    libchromatix_imx386_cpp_hfr_120 \
    libchromatix_imx386_cpp_hfr_240 \
    libchromatix_imx386_cpp_hfr_60 \
    libchromatix_imx386_cpp_liveshot \
    libchromatix_imx386_cpp_snapshot \
    libchromatix_imx386_cpp_video \
    libchromatix_imx386_cpp_video_4k \
    libchromatix_imx386_default_video \
    libchromatix_imx386_default_video_3a \
    libchromatix_imx386_hfr_120 \
    libchromatix_imx386_hfr_120_3a \
    libchromatix_imx386_hfr_240 \
    libchromatix_imx386_hfr_240_3a \
    libchromatix_imx386_hfr_60 \
    libchromatix_imx386_hfr_60_3a \
    libchromatix_imx386_mono_4k_video_3a \
    libchromatix_imx386_mono_common \
    libchromatix_imx386_mono_cpp_hfr_120 \
    libchromatix_imx386_mono_cpp_hfr_240 \
    libchromatix_imx386_mono_cpp_hfr_60 \
    libchromatix_imx386_mono_cpp_liveshot \
    libchromatix_imx386_mono_cpp_snapshot \
    libchromatix_imx386_mono_cpp_video \
    libchromatix_imx386_mono_cpp_video_4k \
    libchromatix_imx386_mono_default_video \
    libchromatix_imx386_mono_default_video_3a \
    libchromatix_imx386_mono_hfr_120 \
    libchromatix_imx386_mono_hfr_120_3a \
    libchromatix_imx386_mono_hfr_240 \
    libchromatix_imx386_mono_hfr_240_3a \
    libchromatix_imx386_mono_hfr_60 \
    libchromatix_imx386_mono_hfr_60_3a \
    libchromatix_imx386_mono_postproc \
    libchromatix_imx386_mono_snapshot \
    libchromatix_imx386_mono_video_4k \
    libchromatix_imx386_mono_zsl_preview_3a \
    libchromatix_imx386_postproc \
    libchromatix_imx386_snapshot \
    libchromatix_imx386_video_4k \
    libchromatix_imx386_zsl_preview_3a \
    libchromatix_mot_ov5675_common \
    libchromatix_mot_ov5675_cpp_hfr_120 \
    libchromatix_mot_ov5675_cpp_hfr_60 \
    libchromatix_mot_ov5675_cpp_liveshot \
    libchromatix_mot_ov5675_cpp_preview \
    libchromatix_mot_ov5675_cpp_snapshot \
    libchromatix_mot_ov5675_cpp_snapshot_custom \
    libchromatix_mot_ov5675_cpp_video_full \
    libchromatix_mot_ov5675_hfr_120 \
    libchromatix_mot_ov5675_hfr_120_3a \
    libchromatix_mot_ov5675_hfr_60 \
    libchromatix_mot_ov5675_hfr_60_3a \
    libchromatix_mot_ov5675_postproc \
    libchromatix_mot_ov5675_snapshot \
    libchromatix_mot_ov5675_video_full \
    libchromatix_mot_ov5675_zsl_preview_3a \
    libchromatix_mot_ov5675_zsl_video_3a \
    libchromatix_mot_ov5695_common \
    libchromatix_mot_ov5695_cpp_hfr_120 \
    libchromatix_mot_ov5695_cpp_liveshot \
    libchromatix_mot_ov5695_cpp_snapshot \
    libchromatix_mot_ov5695_cpp_video \
    libchromatix_mot_ov5695_default_video \
    libchromatix_mot_ov5695_default_video_3a \
    libchromatix_mot_ov5695_hfr_120 \
    libchromatix_mot_ov5695_hfr_120_3a \
    libchromatix_mot_ov5695_postproc \
    libchromatix_mot_ov5695_snapshot \
    libchromatix_mot_ov5695_snapshot_3a \
    libchromatix_mot_ov8856_common \
    libchromatix_mot_ov8856_cpp_ds_chromatix \
    libchromatix_mot_ov8856_cpp_hfr_120 \
    libchromatix_mot_ov8856_cpp_liveshot \
    libchromatix_mot_ov8856_cpp_preview \
    libchromatix_mot_ov8856_cpp_snapshot \
    libchromatix_mot_ov8856_cpp_snapshot_custom \
    libchromatix_mot_ov8856_cpp_us_chromatix \
    libchromatix_mot_ov8856_cpp_video \
    libchromatix_mot_ov8856_default_video \
    libchromatix_mot_ov8856_hfr_120 \
    libchromatix_mot_ov8856_hfr_120_3a \
    libchromatix_mot_ov8856_postproc \
    libchromatix_mot_ov8856_snapshot \
    libchromatix_mot_ov8856_zsl_preview_3a \
    libchromatix_mot_ov8856_zsl_video_3a \
    libchromatix_mot_s5k3p8sp_4m_cpp_snapshot \
    libchromatix_mot_s5k3p8sp_common \
    libchromatix_mot_s5k3p8sp_cpp_hfr_120 \
    libchromatix_mot_s5k3p8sp_cpp_liveshot \
    libchromatix_mot_s5k3p8sp_cpp_preview \
    libchromatix_mot_s5k3p8sp_cpp_snapshot \
    libchromatix_mot_s5k3p8sp_cpp_snapshot_custom \
    libchromatix_mot_s5k3p8sp_cpp_video \
    libchromatix_mot_s5k3p8sp_default_preview_3a \
    libchromatix_mot_s5k3p8sp_default_video_3a \
    libchromatix_mot_s5k3p8sp_hfr_120 \
    libchromatix_mot_s5k3p8sp_hfr_120_3a \
    libchromatix_mot_s5k3p8sp_postproc \
    libchromatix_mot_s5k3p8sp_preview \
    libchromatix_mot_s5k3p8sp_snapshot \
    libchromatix_mot_s5k4h7_common \
    libchromatix_mot_s5k4h7_cpp_hfr_120 \
    libchromatix_mot_s5k4h7_cpp_liveshot \
    libchromatix_mot_s5k4h7_cpp_preview \
    libchromatix_mot_s5k4h7_cpp_snapshot \
    libchromatix_mot_s5k4h7_cpp_snapshot_custom \
    libchromatix_mot_s5k4h7_cpp_video_full \
    libchromatix_mot_s5k4h7_hfr_120 \
    libchromatix_mot_s5k4h7_hfr_120_3a \
    libchromatix_mot_s5k4h7_postproc \
    libchromatix_mot_s5k4h7_snapshot \
    libchromatix_mot_s5k4h7_video_full \
    libchromatix_mot_s5k4h7_zsl_preview_3a \
    libchromatix_mot_s5k4h7_zsl_video_3a \
    libchromatix_mot_s5k4h8_aux_common \
    libchromatix_mot_s5k4h8_aux_cpp_hfr_120 \
    libchromatix_mot_s5k4h8_aux_cpp_hfr_60 \
    libchromatix_mot_s5k4h8_aux_cpp_liveshot \
    libchromatix_mot_s5k4h8_aux_cpp_preview \
    libchromatix_mot_s5k4h8_aux_cpp_snapshot \
    libchromatix_mot_s5k4h8_aux_cpp_snapshot_custom \
    libchromatix_mot_s5k4h8_aux_cpp_video_full \
    libchromatix_mot_s5k4h8_aux_hfr_120 \
    libchromatix_mot_s5k4h8_aux_hfr_120_3a \
    libchromatix_mot_s5k4h8_aux_hfr_60 \
    libchromatix_mot_s5k4h8_aux_hfr_60_3a \
    libchromatix_mot_s5k4h8_aux_postproc \
    libchromatix_mot_s5k4h8_aux_snapshot \
    libchromatix_mot_s5k4h8_aux_video_full \
    libchromatix_mot_s5k4h8_aux_zsl_preview_3a \
    libchromatix_mot_s5k4h8_aux_zsl_video_3a \
    libchromatix_mot_s5k4h8_common \
    libchromatix_mot_s5k4h8_cpp_hfr_120 \
    libchromatix_mot_s5k4h8_cpp_liveshot \
    libchromatix_mot_s5k4h8_cpp_preview \
    libchromatix_mot_s5k4h8_cpp_snapshot \
    libchromatix_mot_s5k4h8_cpp_snapshot_custom \
    libchromatix_mot_s5k4h8_cpp_video_full \
    libchromatix_mot_s5k4h8_hfr_120 \
    libchromatix_mot_s5k4h8_hfr_120_3a \
    libchromatix_mot_s5k4h8_postproc \
    libchromatix_mot_s5k4h8_snapshot \
    libchromatix_mot_s5k4h8_video_full \
    libchromatix_mot_s5k4h8_zsl_preview_3a \
    libchromatix_mot_s5k4h8_zsl_video_3a \
    libchromatix_s5k2l7sa_1080p_preview_3a \
    libchromatix_s5k2l7sa_1080p_video_3a \
    libchromatix_s5k2l7sa_4k_preview_3a \
    libchromatix_s5k2l7sa_4k_video_3a \
    libchromatix_s5k2l7sa_common \
    libchromatix_s5k2l7sa_cpp_hfr_120 \
    libchromatix_s5k2l7sa_cpp_hfr_240 \
    libchromatix_s5k2l7sa_cpp_hfr_60 \
    libchromatix_s5k2l7sa_cpp_liveshot \
    libchromatix_s5k2l7sa_cpp_preview \
    libchromatix_s5k2l7sa_cpp_snapshot \
    libchromatix_s5k2l7sa_cpp_snapshot_custom \
    libchromatix_s5k2l7sa_cpp_video \
    libchromatix_s5k2l7sa_cpp_video_4k \
    libchromatix_s5k2l7sa_default_preview_3a \
    libchromatix_s5k2l7sa_default_video \
    libchromatix_s5k2l7sa_default_video_3a \
    libchromatix_s5k2l7sa_fullsize_preview_3a \
    libchromatix_s5k2l7sa_fullsize_video_3a \
    libchromatix_s5k2l7sa_hfr_120 \
    libchromatix_s5k2l7sa_hfr_120_3a \
    libchromatix_s5k2l7sa_hfr_240 \
    libchromatix_s5k2l7sa_hfr_240_3a \
    libchromatix_s5k2l7sa_hfr_60 \
    libchromatix_s5k2l7sa_hfr_60_3a \
    libchromatix_s5k2l7sa_postproc \
    libchromatix_s5k2l7sa_preview \
    libchromatix_s5k2l7sa_snapshot \
    libchromatix_s5k2l7sa_video_4k \
    libcppf \
    libdepthmapwrapper \
    libfastcvadsp_stub \
    libflash_aw3643_front \
    libflash_aw3643_rear \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_gt24c128b_mono_eeprom \
    libmmcamera_gt24c128b_rgb_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx386 \
    libmmcamera_imx386_mono \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_mot_ov5675 \
    libmmcamera_mot_ov5675_eeprom \
    libmmcamera_mot_ov5695 \
    libmmcamera_mot_ov5695_eeprom \
    libmmcamera_mot_ov8856 \
    libmmcamera_mot_ov8856_eeprom \
    libmmcamera_mot_s5k2l7 \
    libmmcamera_mot_s5k2l7sa \
    libmmcamera_mot_s5k2l7sa_eeprom \
    libmmcamera_mot_s5k2l7sa_pdaf \
    libmmcamera_mot_s5k3p8sp \
    libmmcamera_mot_s5k3p8sp_eeprom \
    libmmcamera_mot_s5k4h7 \
    libmmcamera_mot_s5k4h7_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h7_eeprom \
    libmmcamera_s5k4h7a8s_eeprom \
    libmmcamera_s5k4h8 \
    libmmcamera_s5k4h8_aux \
    libmmcamera_s5k4h8_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_lux_standardization \
    libmotimager_utils \
    libpn553_fw \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveFaceRecognition \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libzaf_algs \
    libzaf_core \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libdrmfs \
    libdrmtime \
    libhdcpsrm \
    liboemcrypto \
    libqisl \
    librpmb \
    libsecureui_svcsock \
    libssd \
    vendor.qti.hardware.tui_comm@1.0 \
    MotoSignatureApp \
    ModFmwkProxyService \
    ModService \
    MotCamera2 \
    ProjectorApp \
    com.motorola.motosignature \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-fpcservice \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    motorola.hardware.health@1.0-service \
    qseecomd \
    sensors.qti

PRODUCT_PACKAGES += \
    system_priv-app_ModFmwkProxyService_lib_arm64_libmodhw_so \
    system_priv-app_ModFmwkProxyService_lib_arm64_libvibratorhw_so
